package GlassWorksInvoice;

import java.awt.Container;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*	Class:		InvoiceGUI
*	File:		InvoiceGUI.java
*	Description:	An invoice sample program for Sara's Glass Works
*                       company. It provides calculation for purchasing
*                       glass works with tax rate applied.
*	@author:	Ryu Muthui
*	Environment:	PC, Windows 7, jdk:1.7.0_10, NetBeans IDE 7.2
*	Date:		1/23/2013
*	@version:	1.01
*       @see:           javax.swing.JFrame 
*	History Log:	Created 1/23/2013
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

public class InvoiceGUI extends javax.swing.JFrame 
{
    //Declared class wide variables.
    int item1Count, item2Count, item3Count;
    final double LAMP_PRICE = 225.00, FROG_PRICE = 185.00,HEART_PRICE = 155.00;
    final double TAX_RATE = 0.098;
    double lampSubtotal; 
    double frogSubtotal;
    double heartSubtotal;
    
    //Sets Currency format display.
    DecimalFormat currency = new DecimalFormat("$#,###,##0.00");
    
    //Creates new form InvoiceGUI.
    public InvoiceGUI() 
    {
        initComponents();
        
        //Sets the invoice number to "0".
        invoicenumberJFormattedTextField.setText("0");
        
        //Sets the form to display in the center on start up.
        setLocationRelativeTo(null);

        //Sets the default button on the form.
        this.getRootPane().setDefaultButton(calculateJButton);

        //Sets the constant prices for each of the item type.
        lampPriceJLabel.setText(String.format ("$%.2f", LAMP_PRICE));
        frogPriceJLabel.setText(String.format ("$%.2f", FROG_PRICE));
        heartPriceJlabel.setText(String.format ("$%.2f", + HEART_PRICE));

        //Sets the date to the invoice form.
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        java.util.Date date = new java.util.Date();
        dateJLabel.setText("Date: " + dateFormat.format(date));
        
        //Sets the background color of the form.
        Container background = this.getContentPane();
        background.setBackground(new java.awt.Color(204,255,255));
        
        //Sets icon image on form.
        this.setIconImage(Toolkit.getDefaultToolkit()
                .getImage("src/GlassWorksInvoice/GlassIcon.png"));
        
        //Disable keyboard edits in the Jspinner and make it read only.
        JFormattedTextField lamp =
        ((JSpinner.DefaultEditor)lampJSpinner.getEditor()).getTextField();
        lamp.setEditable(false);
        
        JFormattedTextField frog =
        ((JSpinner.DefaultEditor)frogJSpinner.getEditor()).getTextField();
        frog.setEditable(false);
        
        JFormattedTextField heart =
        ((JSpinner.DefaultEditor)heartJSpinner.getEditor()).getTextField();
        heart.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        artpieceJLabel = new javax.swing.JLabel();
        quantityLlabel = new javax.swing.JLabel();
        priceJLabel = new javax.swing.JLabel();
        extendedTotalJLabel = new javax.swing.JLabel();
        imageLampJLabel = new javax.swing.JLabel();
        imageFrogJlabel = new javax.swing.JLabel();
        imageHeartJlabel = new javax.swing.JLabel();
        calculateJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        subTotalJLabel1 = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalJLabel = new javax.swing.JLabel();
        invoiceNumberJLabel = new javax.swing.JLabel();
        dateJLabel = new javax.swing.JLabel();
        lampJSpinner = new javax.swing.JSpinner();
        frogJSpinner = new javax.swing.JSpinner();
        heartJSpinner = new javax.swing.JSpinner();
        lampPriceJLabel = new javax.swing.JLabel();
        frogPriceJLabel = new javax.swing.JLabel();
        heartPriceJlabel = new javax.swing.JLabel();
        lampSubtotalJTextField = new javax.swing.JTextField();
        frogSubtotalJTextField = new javax.swing.JTextField();
        heartSubtotalJTextField = new javax.swing.JTextField();
        subtotalJTextField = new javax.swing.JTextField();
        taxJTextField = new javax.swing.JTextField();
        totalJTextField = new javax.swing.JTextField();
        invoicenumberJFormattedTextField = new javax.swing.JFormattedTextField();
        JMenuBar = new javax.swing.JMenuBar();
        FileJMenu = new javax.swing.JMenu();
        calculateJMenuItem = new javax.swing.JMenuItem();
        clearJMenuItem = new javax.swing.JMenuItem();
        JSeparator = new javax.swing.JPopupMenu.Separator();
        quitJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sara's Glass Works");
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        titleJLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(255, 0, 0));
        titleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GlassWorksInvoice/Glass.jpg"))); // NOI18N
        titleJLabel.setText("Sara's Glass Works");
        titleJLabel.setToolTipText("Welcome to Sara's Glass Works!");

        artpieceJLabel.setText("Art Piece:");

        quantityLlabel.setText("Quantity:");

        priceJLabel.setText("Price:");

        extendedTotalJLabel.setText("Extended Total:");

        imageLampJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GlassWorksInvoice/lamp.JPG"))); // NOI18N
        imageLampJLabel.setToolTipText("Lamp costs $225.00 each, there are 10 available.");

        imageFrogJlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GlassWorksInvoice/frog.jpg"))); // NOI18N
        imageFrogJlabel.setToolTipText("Frog costs $185.00 each, there are 20 available.");

        imageHeartJlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GlassWorksInvoice/heart.jpg"))); // NOI18N
        imageHeartJlabel.setToolTipText("Heart costs $155.00 each, there are 6 available.");

        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate");
        calculateJButton.setToolTipText("Select to calculate the total cost.");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });

        clearJButton.setMnemonic('L');
        clearJButton.setText("Clear");
        clearJButton.setToolTipText("Select to clear all fields.");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.setToolTipText("Select to exit the program.");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });

        subTotalJLabel1.setText("Sub Total:");

        taxLabel.setText("Tax:");

        totalJLabel.setText("Total:");

        invoiceNumberJLabel.setText("Invoice Number:");

        dateJLabel.setText("Date:");
        dateJLabel.setToolTipText("Now showing today's date.");

        lampJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        lampJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lampJSpinnerStateChanged(evt);
            }
        });

        frogJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        frogJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frogJSpinnerStateChanged(evt);
            }
        });

        heartJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 6, 1));
        heartJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heartJSpinnerStateChanged(evt);
            }
        });

        lampPriceJLabel.setText("0.00");

        frogPriceJLabel.setText("0.00");

        heartPriceJlabel.setText("0.00");

        lampSubtotalJTextField.setEditable(false);
        lampSubtotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lampSubtotalJTextField.setText("$0.00");

        frogSubtotalJTextField.setEditable(false);
        frogSubtotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frogSubtotalJTextField.setText("$0.00");

        heartSubtotalJTextField.setEditable(false);
        heartSubtotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        heartSubtotalJTextField.setText("$0.00");

        subtotalJTextField.setEditable(false);
        subtotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        subtotalJTextField.setText("$0.00");

        taxJTextField.setEditable(false);
        taxJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        taxJTextField.setText("$0.00");

        totalJTextField.setEditable(false);
        totalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalJTextField.setText("$0.00");

        try {
            invoicenumberJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        invoicenumberJFormattedTextField.setToolTipText("Enter a 4 digit invoice number here.");

        FileJMenu.setText("File");

        calculateJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        calculateJMenuItem.setMnemonic('C');
        calculateJMenuItem.setText("Caclulate");
        calculateJMenuItem.setToolTipText("Select to calculate total cost.");
        calculateJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJMenuItemActionPerformed(evt);
            }
        });
        FileJMenu.add(calculateJMenuItem);

        clearJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        clearJMenuItem.setMnemonic('l');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.setToolTipText("Select to calculate total cost.");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJMenuItemActionPerformed(evt);
            }
        });
        FileJMenu.add(clearJMenuItem);
        FileJMenu.add(JSeparator);

        quitJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        quitJMenuItem.setMnemonic('Q');
        quitJMenuItem.setText("Quit");
        quitJMenuItem.setToolTipText("Select to quit program.");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJMenuItemActionPerformed(evt);
            }
        });
        FileJMenu.add(quitJMenuItem);

        JMenuBar.add(FileJMenu);

        helpJMenu.setText("Help");
        helpJMenu.setToolTipText("");

        aboutJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        aboutJMenuItem.setMnemonic('a');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        JMenuBar.add(helpJMenu);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceNumberJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invoicenumberJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageLampJLabel)
                                    .addComponent(imageFrogJlabel)
                                    .addComponent(imageHeartJlabel)
                                    .addComponent(artpieceJLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(quantityLlabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(heartJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(frogJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lampJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quitJButton))
                            .addComponent(calculateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(heartPriceJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(priceJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(frogPriceJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lampPriceJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lampSubtotalJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(heartSubtotalJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                                .addComponent(frogSubtotalJTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(extendedTotalJLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(totalJLabel)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(subTotalJLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(taxLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(taxJTextField)
                                            .addComponent(subtotalJTextField)
                                            .addComponent(totalJTextField))))
                                .addGap(28, 28, 28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNumberJLabel)
                    .addComponent(invoicenumberJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateJLabel))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityLlabel)
                        .addComponent(priceJLabel)
                        .addComponent(extendedTotalJLabel))
                    .addComponent(artpieceJLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imageLampJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageFrogJlabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lampJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lampPriceJLabel)
                                    .addComponent(lampSubtotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(frogJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(frogPriceJLabel)
                                    .addComponent(frogSubtotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageHeartJlabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(heartJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heartPriceJlabel)
                                    .addComponent(heartSubtotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addComponent(calculateJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearJButton)
                            .addComponent(quitJButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subTotalJLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalJLabel))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        //Click to exit program.
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        //Click to set all fields back to default.
        lampSubtotalJTextField.setText("$0.00");
        frogSubtotalJTextField.setText("$0.00");
        heartSubtotalJTextField.setText("$0.00");
        subtotalJTextField.setText("$0.00");
        taxJTextField.setText("$0.00");
        totalJTextField.setText("$0.00");
        lampJSpinner.setValue(0);
        frogJSpinner.setValue(0);
        heartJSpinner.setValue(0);
        invoicenumberJFormattedTextField.setText("0");
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        //Select to calculate total cost.
        
        //Diclared variables for calculations.
        double TotalCost;
        double SubTotal;
        double Tax;
        
        //Read inputs.
        item1Count = Integer.parseInt(lampJSpinner.getValue().toString());
        item2Count = Integer.parseInt(frogJSpinner.getValue().toString());
        item3Count = Integer.parseInt(heartJSpinner.getValue().toString());
        
        //Calulate the inputs.
        lampSubtotal = item1Count * LAMP_PRICE;
        frogSubtotal = item2Count * FROG_PRICE;
        heartSubtotal = item3Count * HEART_PRICE;
        SubTotal = lampSubtotal + frogSubtotal + heartSubtotal;
        Tax = SubTotal * TAX_RATE;
        TotalCost = SubTotal + Tax;
        
        //Display outputs.
        lampSubtotalJTextField.setText(currency.format(lampSubtotal));
        frogSubtotalJTextField.setText(currency.format(frogSubtotal));
        heartSubtotalJTextField.setText(currency.format(heartSubtotal));
        subtotalJTextField.setText(currency.format(SubTotal));
        taxJTextField.setText(currency.format(Tax));
        totalJTextField.setText(currency.format(TotalCost));

    }//GEN-LAST:event_calculateJButtonActionPerformed

    private void lampJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lampJSpinnerStateChanged
        //Enables to dynamically calculate the lamp price.
        int lampCount;
        lampCount = Integer.parseInt(lampJSpinner.getValue().toString());
        lampSubtotal = lampCount * LAMP_PRICE;
        lampSubtotalJTextField.setText(currency.format(lampSubtotal)); 
    }//GEN-LAST:event_lampJSpinnerStateChanged

    private void frogJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_frogJSpinnerStateChanged
        //Enables to dynamically calculate the frog price.
        int frogCount;
        frogCount = Integer.parseInt(frogJSpinner.getValue().toString());
        frogSubtotal = frogCount * FROG_PRICE;
        frogSubtotalJTextField.setText(currency.format(frogSubtotal));
    }//GEN-LAST:event_frogJSpinnerStateChanged

    private void heartJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heartJSpinnerStateChanged
        //Enables to dynamically calculate the heart price.
        int heartCount;
        heartCount = Integer.parseInt(heartJSpinner.getValue().toString());
        heartSubtotal = heartCount * HEART_PRICE;
        heartSubtotalJTextField.setText(currency.format(heartSubtotal));
    }//GEN-LAST:event_heartJSpinnerStateChanged

    private void calculateJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJMenuItemActionPerformed
        //Select to calculate total cost.
        calculateJButtonActionPerformed(evt);
    }//GEN-LAST:event_calculateJMenuItemActionPerformed

    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJMenuItemActionPerformed
        //Select to set all fields back to default.
        clearJButtonActionPerformed(evt);
    }//GEN-LAST:event_clearJMenuItemActionPerformed

    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        //Sets the About Form to be visible.
        AboutForm myAbout = new AboutForm();
        myAbout.setVisible(true);
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJMenuItemActionPerformed
        //Select to exit program.
        System.exit(0);
    }//GEN-LAST:event_quitJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InvoiceGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileJMenu;
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JPopupMenu.Separator JSeparator;
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JLabel artpieceJLabel;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JMenuItem calculateJMenuItem;
    private javax.swing.JButton clearJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JLabel dateJLabel;
    private javax.swing.JLabel extendedTotalJLabel;
    private javax.swing.JSpinner frogJSpinner;
    private javax.swing.JLabel frogPriceJLabel;
    private javax.swing.JTextField frogSubtotalJTextField;
    private javax.swing.JSpinner heartJSpinner;
    private javax.swing.JLabel heartPriceJlabel;
    private javax.swing.JTextField heartSubtotalJTextField;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JLabel imageFrogJlabel;
    private javax.swing.JLabel imageHeartJlabel;
    private javax.swing.JLabel imageLampJLabel;
    private javax.swing.JLabel invoiceNumberJLabel;
    private javax.swing.JFormattedTextField invoicenumberJFormattedTextField;
    private javax.swing.JSpinner lampJSpinner;
    private javax.swing.JLabel lampPriceJLabel;
    private javax.swing.JTextField lampSubtotalJTextField;
    private javax.swing.JLabel priceJLabel;
    private javax.swing.JLabel quantityLlabel;
    private javax.swing.JButton quitJButton;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JLabel subTotalJLabel1;
    private javax.swing.JTextField subtotalJTextField;
    private javax.swing.JTextField taxJTextField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel totalJLabel;
    private javax.swing.JTextField totalJTextField;
    // End of variables declaration//GEN-END:variables
}
