package Craps;

import java.awt.Container;
import java.awt.Toolkit;

/**
*Class:         AboutCraps
*File:		AboutCraps.java
*Description:	A form to display information about the Game of Craps and
*               what this application simulates.
*@author:	Ryu Muthui
*Environment:	PC, Windows 7, jdk:1.7.0_10, NetBeans IDE 7.2
*Date:		03/06/2013
*@version:	1.01
*@see:          java.awt.Container;
*@see:          java.awt.Toolkit;
*History Log:	Created 2/26/2013, Last updated 03/06/2013
*/
public class AboutCraps extends javax.swing.JFrame {

    /**
     * Creates new form AboutCraps and sets its initial states.
     */
    public AboutCraps() 
    {
        initComponents();
        
        
        //Sets the form to display in the center on start up.
        setLocationRelativeTo(null);
        
        //Sets the default button on the form.
        this.getRootPane().setDefaultButton(closeJButton);
        
        //Sets the background color of the form.
        Container background = this.getContentPane();
        background.setBackground(new java.awt.Color(51,153,255));
        
        //Sets icon image on form.
        this.setIconImage(Toolkit.getDefaultToolkit()
                .getImage("src/Craps/Images/die6.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeJButton = new javax.swing.JButton();
        crapsLogoJLabel = new javax.swing.JLabel();
        aboutJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About the Game of Craps");
        setResizable(false);

        closeJButton.setMnemonic('C');
        closeJButton.setText("Close");
        closeJButton.setToolTipText("Select to Close About Window.");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        crapsLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Craps/Images/CrapsAboutIcon.jpg"))); // NOI18N
        crapsLogoJLabel.setToolTipText("Welcome to Craps Simulation Game.");
        crapsLogoJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        aboutJLabel.setText("<HTML> \nGame Rules: <BR>A player rolls two dice. Each dice has six faces. These faces contain one, two, three, four, five, and six spots, respectively. After the dice have come to rest, the sum of the spots on the two upward faces is calculated. <BR><BR>\nIf the sum is 7 or 11 on the first throw, the player wins. If the sum is 2, 3, or 12 on the first throw (called “craps”), the player loses (i.e., the “house” wins). If the sum is 4, 5, 6, 8, 9 or 10 on the first throw, that sum becomes the player’s “point.”<BR><BR>\nTo win, you must continue rolling the dice until you “make your point” (i.e., roll your point value). The player loses by rolling a 7 before making the point.<BR><BR>\n\nThis program is to simulate the game of craps. It keeps track of number of games played, won/lost, and winning percentage of the games played. It also keeps track of each of the faces rolled and the percentage of each faced roll during the game session. The Save Feature will save the statistics of each game session to an external text file in the source folder.<BR><BR>\nWith Gambling Feature Enabled:<BR> The player can simulate gambling with the game of craps. The player starts off with a bank balance of $1000 and can double their winnings with the amount they placed if they win. If they lose, the player will lose the same amount as they betted from their bank balance. Exiting Gambling or Clearing will reset this feature to the starting bank balance.<BR><BR>\nAuthor: Ryu Muthui <BR><BR>\nVersion:1.01; Created 03/06/2013<BR>\nPlatform: PC, Windows 7, jdk:1.7.0_10, NetBeans IDE 7.2 <BR><BR>\nCopyright: Ryu Muthui Productions (2013)<BR>\n</HTML>\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aboutJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(crapsLogoJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(closeJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crapsLogoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeJButton)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Closes the About form when clicked.
 * @param evt Click Event.
 */
    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
         //Click to close About Form.
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutCraps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutCraps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutCraps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutCraps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutCraps().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutJLabel;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel crapsLogoJLabel;
    // End of variables declaration//GEN-END:variables
}
